#!/usr/bin/env python

import time
import serial
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

ser = serial.Serial(
    port='/dev/ttyS0',  # Corrected the serial port path
    baudrate=9600,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1
)

counter = 0

while True:
    ser.write(str.encode('Write counter: %d \n' % counter))
    time.sleep(1)
    counter += 1
    x = ser.readline().strip().decode()  # Decoded the received data to string
    print(x)
